{"approachDistance": 0.5,
"cruiseCurrentAlpha": 100,
"cruiseCurrentBeta": 100,
"motorRpmAlpha": 5000,
"motorRpmBeta": 5000,
"correctionMotorRpmAlpha": 5000,
"correctionMotorRpmBeta": 5000,
"nbTargets": 1000,
"numberOfRepetitions": 5,
"numberOfCorrections": 2,
"stopOnDesiredError": true,
"desiredTargetError": 5.0,
"maxTargetError": 200.0,
"alphaTestRange": [0,
360],
"betaTestRange": [0,
360],
"workSpaceMargin": 20.0,
"hardstopMargin": 2.0,
"extendedBetaTest": true,
"avoidTargetRandomize": true,
"refoldAfterTarget": true}