{"approachDistance": 0.5,
"cruiseCurrentAlpha": 100,
"cruiseCurrentBeta": 100,
"motorRpmAlpha": 5120,
"motorRpmBeta": 5120,
"correctionMotorRpmAlpha": 5120,
"correctionMotorRpmBeta": 5120,
"nbTargets": 20,
"numberOfRepetitions": 2,
"numberOfCorrections": 2,
"stopOnDesiredError": true,
"desiredTargetError": 5.0,
"maxTargetError": 200.0,
"alphaTestRange": [0,
36],
"betaTestRange": [0,
36],
"workSpaceMargin": 20.0,
"hardstopMargin": 2.0,
"extendedBetaTest": true,
"avoidTargetRandomize": true,
"refoldAfterTarget": false}